# Generated by Django 4.2 on 2023-06-20 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 20)),
        ),
        migrations.AddField(
            model_name='news',
            name='news_text',
            field=models.TextField(blank=True),
        ),
    ]
