# Generated by Django 4.2 on 2023-06-21 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_date_news_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 21)),
        ),
    ]
