# Generated by Django 4.2 on 2023-06-22 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 22)),
        ),
    ]
