# Generated by Django 4.2 on 2023-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=40)),
                ('firm_adress', models.CharField(max_length=255)),
                ('firm_email', models.CharField(max_length=100)),
                ('firm_tel', models.CharField(max_length=20)),
            ],
        ),
    ]
