# Generated by Django 4.2 on 2023-06-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_sign', models.CharField(max_length=100)),
                ('answer_sign', models.CharField(max_length=100)),
            ],
        ),
    ]
