# Generated by Django 4.2 on 2023-06-20 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='answer_for_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 20)),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_sign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_sign',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
