# Generated by Django 4.2 on 2023-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comments_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
