# Generated by Django 4.2 on 2023-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comments_comment_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_for_comment',
            field=models.TextField(blank=True, verbose_name='Ответ на отзыв'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_sign',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись к ответу'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_sign',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
    ]
