# Generated by Django 4.2 on 2023-07-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Занесено в базу данных', models.BooleanField(auto_created=True, default=False, verbose_name='Занесено в базу данных')),
                ('Дата заявки', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('Клиент', models.CharField(blank=True, max_length=50, verbose_name='Клиент')),
                ('Вид заявки', models.CharField(blank=True, max_length=25, verbose_name='Вид заявки')),
                ('Описание неисправности', models.CharField(blank=True, max_length=256, verbose_name='Описание неисправности')),
                ('Телефон', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('Имя', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('e-mail', models.CharField(blank=True, max_length=50, verbose_name='e-mail')),
            ],
        ),
    ]
