# Generated by Django 4.2 on 2023-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demands',
            name='Аппарат',
            field=models.CharField(blank=True, max_length=30, verbose_name='Аппарат'),
        ),
        migrations.AddField(
            model_name='demands',
            name='Серийный номер',
            field=models.CharField(blank=True, max_length=25, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='demands',
            name='Описание неисправности',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание неисправности'),
        ),
    ]
