# Generated by Django 4.2 on 2023-07-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_demands_адрес'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demands',
            old_name='Адрес',
            new_name='demand_address',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Клиент',
            new_name='demand_client',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Дата заявки',
            new_name='demand_date',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Вид заявки',
            new_name='demand_type',
        ),
    ]
