# Generated by Django 4.2 on 2023-07-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_адрес_demands_demand_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demands',
            old_name='Описание неисправности',
            new_name='demand_description',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='e-mail',
            new_name='demand_email',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Имя',
            new_name='demand_fio',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Занесено в базу данных',
            new_name='demand_in_base',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Серийный номер',
            new_name='demand_serial',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Аппарат',
            new_name='demand_tech',
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='Телефон',
            new_name='demand_telephone',
        ),
    ]
