# Generated by Django 4.2 on 2023-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Товар')),
                ('article', models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул')),
                ('catalog_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Каталожный номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('in_stock', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6, verbose_name='Кол-во на складе')),
                ('cat1', models.BigIntegerField(default=0, verbose_name='id раздела 1-ого уровня')),
                ('cat2', models.BigIntegerField(default=0, verbose_name='id раздела 2-ого уровня')),
                ('cat3', models.BigIntegerField(default=0, verbose_name='id раздела 3-ого уровня')),
                ('is_good', models.BooleanField(default=True, verbose_name='Товар/ раздел')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('supplier', models.CharField(blank=True, max_length=4, null=True, verbose_name='Поставшик')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
