# Generated by Django 4.2 on 2023-07-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='cat1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='good',
            name='cat2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='good',
            name='cat3',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='good',
            name='is_good',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='good',
            name='in_stock',
            field=models.DecimalField(db_index=True, decimal_places=2, default=True, max_digits=6),
        ),
    ]
