# Generated by Django 4.2 on 2023-07-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_good_category_good_cat1_good_cat2_good_cat3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='article',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='good',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='good',
            name='supplier',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='in_stock',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
