# Generated by Django 4.2 on 2023-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good_article_good_catalog_number_good_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
